version: '3.8'

services:
  # 个人网站服务
  personal-site:
    build: ./personal-site
    ports:
      - "80:80"
    networks:
      - app-network

  # Todo 应用 (使用现成镜像)
  todo-app:
    build: ./todo-app
    ports:
      - "81:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge