version: '3.8'

services:
  # 个人网站服务
  personal-site:
    image: gaoyifeng123/personal-site:latest
    build: .
    ports:
      - "80:80"
    restart: always

  # Todo 应用 (使用现成镜像)
  todo-app:
    image: docker.io/amir20/dozzle:latest  # 示例Todo应用
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always