version: '3.3'
services:  
  frontend:
    image: gaoyifeng123/234-deploylab-frontend:latest
    pull_policy: always
    ports:
      - "8100:80"

  todo-app:
    image: gaoyifeng123/234-deploylab:latest
    ports:
      - "8101:3000"  
    networks:
      - app-network

networks:
  app-network:
    driver: bridge