version: '3.8'

services:
  personal-site:
    build: ./personal-site
    ports:
      - "8100:80"
    restart: always
    volumes:
      - ./personal-site:/usr/share/nginx/html:ro
    networks:
      - app-network

  todo-app:
    image: docker/getting-started
    ports:
      - "8101:8101"
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge