name: Deploy Applications

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Personal Site
        uses: docker/build-push-action@v2
        with:
          context: ./personal-site
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/personal-site:latest

      - name: Build and push Todo App
        uses: docker/build-push-action@v2
        with:
          context: ./todo-app
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/todo-app:latest

      - name: Copy project files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "."
          target: "/home/ubuntu/final"
          rm: true

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_SERVER }}
          username: ${{ secrets.HOST_USER_NAME }}
          key: ${{ secrets.HOST_SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/final
            docker-compose pull
            docker-compose up -d